apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "metadata"
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.orgName }}/${{ values.appName }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ parameters.owner if parameters.owner else 'user:guest' }} # Ou um valor fixo como 'user:guest'
  system: ${{ parameters.system if parameters.system else '' }} # Adicione se você tiver um parâmetro de sistema
  # Exemplo de relações, ajuste conforme necessário
  # relations:
  #   - type: dependsOn
  #     target: component:default/outro-servico
  #   - type: consumesApi
  #     target: api:default/${{ values.apiPath | replace('/', '') }} # Exemplo usando apiPath